Print all subsequences of a string //POWER SET

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc

TIME:O(2^n)

void printSubsequence(string input, string output)
{
   
    if (input.empty()) {
        cout << output << endl;
        return;
    }
 
    								// output is passed with including
    								// the Ist characther of
    								// Input string
    printSubsequence(input.substr(1), output + input[0]);
 
    								// output is passed without
    								// including the Ist character
    								// of Input string
    printSubsequence(input.substr(1), output);
}
 

OUTPUT:
[abcd, abc, abd, ab, acd, ac, ad, a, bcd, bc, bd, b, cd, c, d, ]




------------------------------------------





USING BIT MANIPULATION
----------------------------



 string str="abc";
    int n=str.length();
    
    for(int num=0;num<pow(2,n);num++)
    {
        string temp="";
        for(int i=0;i<n;i++)
        {
            if(num & (1<<i))
            temp+=str[i];
            
        }
        cout<<temp<<"\n";
    }
    